// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'jaguar_x_print';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String IMAGE_NOT_AVAILABLE = 'assets/Image_not_available.png';
  static const String CREDENTIALS = 'assets/credentials.json';
  static const String JAGUAR = 'assets/logo/jaguar.png';
  static const String USER = 'assets/logo/user.png';
  static const String WHATSAPP_ICON = 'assets/logo/whatsapp-icon.svg';
  static const String CLIENT1 = 'assets/menu/client1.jpg';
  static const String CLIENT2 = 'assets/menu/client2.jpg';
  static const String CM1 = 'assets/menu/cm1.jpg';
  static const String CM2 = 'assets/menu/cm2.jpg';
  static const String ENTRETIEN1 = 'assets/menu/entretien1.jpg';
  static const String ENTRETIEN2 = 'assets/menu/entretien2.jpg';
  static const String PAIEMENT1 = 'assets/menu/paiement1.jpg';
  static const String PAIEMENT2 = 'assets/menu/paiement2.jpg';
}
